### ISSUE TITLE
Projecte Vite

### ISSUE THREAD

**Issue by xxjcaxx** [xxjcaxx/projecteDWECTenda#1]
El product Owner necessita que es cree un projecte Vite amb els fitxers i carpetes necessaris.

- [ ] Executar el comandament corresponent
- [ ] Esborrar els fitxers i codi d'exemple i crear nous favicon i altres.
- [ ] Instal·lar Bootstrap, configurar i provar que funciona

**Comment by quico2003** [comment]
holaaa
